apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-demo
  namespace: flux-system
spec:
  interval: 1m
  path: ./1-demo     # relative to repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-killer
    namespace: flux-system
  targetNamespace: 1-demo

